//AUTH ACTIONS AND STATUS CODES
export const INITIALIZE_AUTH_STATE = "INITIALIZE_AUTH_STATE";
export const INITIALIZE_USER_STATE = "INITIALIZE_USER_STATE";
export const INITIALIZE_STOCK_STATE = "INITIALIZE_STOCK_STATE";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";

export const SIGN_OUT_REQUEST = "SIGN_OUT_REQUEST";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_ERROR = "SIGN_OUT_ERROR";

export const CLEAR_USER_REDUCER = "CLEAR_USER_REDUCER";

//USER ACTIONS
export const URL_CHANGED = "URL_CHANGED";
export const LOAD_PORTFOLIO_FROM_FIREBASE = "LOAD_PORTFOLIO_FROM_FIREBASE";
export const SET_NUMBER_OF_STOCKS_TO_BE_FETCHED = "SET_NUMBER_OF_STOCKS_TO_BE_FETCHED";
export const SET_FETCH_USER_STOCKS_LOCK = "SET_FETCH_USER_STOCKS_LOCK";
export const FETCH_USER_STOCK = "FETCH_USER_STOCK";
export const BALANCE_CHANGED = "BALANCE_CHANGED";
export const SET_POP_UP_MESSAGE = "SET_POP_UP_MESSAGE";
export const STOCK_SOLD = "STOCK_SOLD";
export const STOCK_BOUGHT = "STOCK_BOUGHT";
export const CHANGE_THEME = "CHANGE_THEME";
export const FOUND_USERS = "FOUND_USERS";
export const SEARCHING_FOR_USERS_REQUEST = "SEARCHING_FOR_USERS_REQUEST";

//STOCK ACTIONS AND STATUS CODES
export const SEARCH_STOCK_REQUEST = "SEARCH_STOCK_REQUEST";
export const SEARCH_STOCK_SUCCESS = "SEARCH_STOCK_SUCCESS";
export const SEARCH_STOCK_ERROR = "SEARCH_STOCK_ERROR";

export const FETCH_STOCK_REQUEST = "FETCH_STOCK_REQUEST";
export const FETCH_STOCK_ERROR = "FETCH_STOCK_ERROR";
export const FETCH_STOCK_SUCCESS = "FETCH_STOCK_SUCCESS";

export const FETCH_COMPANY_INFO_REQUEST = "FETCH_COMPANY_INFO_REQUEST";
export const FETCH_COMPANY_INFO_SUCCESS = "FETCH_COMPANY_INFO_SUCCESS";
export const FETCH_COMPANY_INFO_ERROR = "FETCH_COMPANY_INFO_ERROR";

export const TICKER_CHOSEN = "TICKER_CHOSEN";
export const INTERVAL_CHANGE = "INTERVAL_CHANGE";